server:
  port: 9003
eureka :
  client :
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:9001/eureka/,http://localhost:9000/eureka/
instance:
  #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都ip）
  prefer-ip-address : true
  #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
  instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: scn-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dajgh/scn-config-test.git
          username: dajgh
          password: bjgg555github
          search-paths:
            - scn-config-test
      label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
